# Generated by Django 3.0.2 on 2020-02-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0005_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('open_tutor_registrations', models.BooleanField(default=False)),
                ('open_student_registrations', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
    ]
